name: admin-server
component: admin
image:
  name: admin-server
  tag: "0000000"
service:
  port: 9090
spring:
  profiles: docker
config:
  CONFIG_SERVER_URL: http://config-server:8888
initContainers:
  - name: wait-for-config-server
    url: http://config-server:8888/actuator/health
  - name: wait-for-discovery-server
    url: http://discovery-server:8761/actuator/health
